package com.ald.fanbei.api.common.enums;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * @类描述：图片类型
 * @author xiaotianjian 2017年2月28日上午11:49:33
 * @注意：本内容仅限于杭州阿拉丁信息科技股份有限公司内部传阅，禁止外泄以及用于其他的商业目的
 */
public enum ImageType {

	MAIN_IMAGE("MAIN_IMAGE", "主图"), 
	OTHER_IMAGE("OTHER_IMAGE", "幅图"),
	
	ONE_IMAGE_ONE("ONE_IMAGE_ONE", "平铺图主图"),
	
	ONE_PLUS_TWO_MAIN_IMAGE("ONE_PLUS_TWO_MAIN_IMAGE", "1+2(左大右小)主图"),
	ONE_PLUS_TWO_ONE_IMAGE("ONE_PLUS_TWO_ONE_IMAGE", "1+2 第一张附图"),
	ONE_PLUS_TWO_TWO_IMAGE("ONE_PLUS_TWO_TWO_IMAGE", "1+2 第二张附图"),

	//新版
	NEW_ONE_PLUS_TWO_MAIN_IMAGE("NEW_ONE_PLUS_TWO_MAIN_IMAGE", "1+2(左大右小)主图"),
	NEW_ONE_PLUS_TWO_ONE_IMAGE("NEW_ONE_PLUS_TWO_ONE_IMAGE", "1+2 第一张附图"),
	NEW_ONE_PLUS_TWO_TWO_IMAGE("NEW_ONE_PLUS_TWO_TWO_IMAGE", "1+2 第二张附图"),
	
	ONE_PLUS_TWO2_MAIN_IMAGE("ONE_PLUS_TWO2_MAIN_IMAGE", "1+2(上大下小)主图"),
	ONE_PLUS_TWO2_ONE_IMAGE("ONE_PLUS_TWO2_ONE_IMAGE", "1+2 第一张附图"),
	ONE_PLUS_TWO2_TWO_IMAGE("ONE_PLUS_TWO2_TWO_IMAGE", "1+2 第二张附图"),
	
	ONE_PLUS_N_MAIN_IMAGE("ONE_PLUS_N_MAIN_IMAGE", "1+n主图"),
	ONE_PLUS_N_ONE_IMAGE("ONE_PLUS_N_ONE_IMAGE", "1+n第一张图"),
	ONE_PLUS_N_TWO_IMAGE("ONE_PLUS_N_TWO_IMAGE", "1+n第二张图"),
	ONE_PLUS_N_THREE_IMAGE("ONE_PLUS_N_THREE_IMAGE", "1+n第三张图"),
	ONE_PLUS_N_FOUR_IMAGE("ONE_PLUS_N_FOUR_IMAGE", "1+n第四张图"),
	ONE_PLUS_N_BACK_IMAGE("ONE_PLUS_N_BACK_IMAGE", "活动专场背景图"),
	HOME_N_CAROUSEL_IMAGE("HOME_N_CAROUSEL_IMAGE","轮播图片"),
	//轮播+n 的下方图片
	HOME_CAROUSEL_IMAGE("HOME_CAROUSEL_IMAGE","轮播下方图片"),

	//轮播+n 的下方图片
	NEW_HOME_CAROUSEL_IMAGE("NEW_HOME_CAROUSEL_IMAGE","轮播下方图片"),
	NEW_HOME_N_CAROUSEL_IMAGE("NEW_HOME_N_CAROUSEL_IMAGE","轮播图片"),

	// 3/6/9运营位
	MANEY_UP_ONE_IMAGE("MANEY_UP_ONE_IMAGE","3/6/9下方上1图"),
	MANEY_UP_TWO_IMAGE("MANEY_UP_TWO_IMAGE","3/6/9下方上2图"),
	MANEY_UP_THREE_IMAGE("MANEY_UP_THREE_IMAGE","3/6/9下方上3图"),
	MANEY_IN_ONE_IMAGE("MANEY_IN_ONE_IMAGE","3/6/9下方中1图"),
	MANEY_IN_TWO_IMAGE("MANEY_IN_TWO_IMAGE","3/6/9下方中2图"),
	MANEY_IN_THREE_IMAGE("MANEY_IN_THREE_IMAGE","3/6/9下方中3图"),
	MANEY_DOWN_ONE_IMAGE("MANEY_DOWN_ONE_IMAGE","3/6/9下方下1图"),
	MANEY_DOWN_TWO_IMAGE("MANEY_DOWN_TWO_IMAGE","3/6/9下方下2图"),
	MANEY_DOWN_THREE_IMAGE("MANEY_DOWN_THREE_IMAGE","3/6/9下方下2图"),

	//返利小贴士
	SEARCH_REBATE_PICTURES_ONE("SEARCH_REBATE_PICTURES_ONE","返利小贴士图1"),
	SEARCH_REBATE_PICTURES_TWO("SEARCH_REBATE_PICTURES_TWO","返利小贴士图2"),
	SEARCH_REBATE_PICTURES_THREE("SEARCH_REBATE_PICTURES_THREE","返利小贴士图3"),
	ONE_IMAGE_FINANCIAL_ONE("ONE_IMAGE_FINANCIAL_ONE","金融楼层图"),
	ONE_IMAGE_BRAND_ONE("ONE_IMAGE_BRAND_ONE","逛逛楼层图"),
	ONE_IMAGE_ECOMMERCE_ONE("ONE_IMAGE_ECOMMERCE_ONE","电商楼层图"),
	
	
	// 常驻运营位置
	HOME_FOUR_IMAGE_NOMAL_POSITION_LEFT_UP("HOME_FOUR_IMAGE_NOMAL_POSITION_LEFT_UP","左上"),
	HOME_FOUR_IMAGE_NOMAL_POSITION_RIGHT_UP("HOME_FOUR_IMAGE_NOMAL_POSITION_RIGHT_UP","右上"),
	HOME_FOUR_IMAGE_NOMAL_POSITION_LEFT_DOWN("HOME_FOUR_IMAGE_NOMAL_POSITION_LEFT_DOWN","左下"),
	HOME_FOUR_IMAGE_NOMAL_POSITION_RIGHT_DOWN("HOME_FOUR_IMAGE_NOMAL_POSITION_RIGHT_DOWN","右下"),
	
	// 逛逛运营位置
	HOME_FOUR_IMAGE_BRAND_POSITION_ONE("HOME_FOUR_IMAGE_BRAND_POSITION_ONE","1"),
	HOME_FOUR_IMAGE_BRAND_POSITION_TWO("HOME_FOUR_IMAGE_BRAND_POSITION_TWO","2"),
	HOME_FOUR_IMAGE_BRAND_POSITION_TRHEE("HOME_FOUR_IMAGE_BRAND_POSITION_TRHEE","3"),
	HOME_FOUR_IMAGE_BRAND_POSITION_FOUR("HOME_FOUR_IMAGE_BRAND_POSITION_FOUR","4"),
	
	// 电商运营位
	HOME_IMAGE_ECOMMERCE_POSITION_LEFT_UP("HOME_IMAGE_ECOMMERCE_POSITION_LEFT_UP",""),
	HOME_IMAGE_ECOMMERCE_POSITION_RIGHT_UP("HOME_IMAGE_ECOMMERCE_POSITION_RIGHT_UP",""),
	HOME_IMAGE_ECOMMERCE_POSITION_MID_MID("HOME_IMAGE_ECOMMERCE_POSITION_MID_MID",""),
	HOME_IMAGE_ECOMMERCE_POSITION_LEFT_MID("HOME_IMAGE_ECOMMERCE_POSITION_LEFT_MID",""),
	HOME_IMAGE_ECOMMERCE_POSITION_LEFT_DOWN("HOME_IMAGE_ECOMMERCE_POSITION_LEFT_DOWN",""),
	HOME_IMAGE_ECOMMERCE_POSITION_MID_DOWN("HOME_IMAGE_ECOMMERCE_POSITION_MID_DOWN",""),
	HOME_IMAGE_ECOMMERCE_POSITION_RIGHT_DOWN("HOME_IMAGE_ECOMMERCE_POSITION_RIGHT_DOWN","")
	;
	
	private String code;

	private String description;

	private static Map<String, ImageType> codeRoleTypeMap = null;

	ImageType(String code, String description) {
		this.code = code;
		this.description = description;
	}

	public static ImageType findEnumByCode(String code) {
		for (ImageType goodSource : ImageType.values()) {
			if (goodSource.getCode().equals(code)) {
				return goodSource;
			}
		}
		return null;
	}

	public static Map<String, ImageType> getCodeRoleTypeMap() {
		if (codeRoleTypeMap != null && codeRoleTypeMap.size() > 0) {
			return codeRoleTypeMap;
		}
		codeRoleTypeMap = new HashMap<String, ImageType>();
		for (ImageType item : ImageType.values()) {
			codeRoleTypeMap.put(item.getCode(), item);
		}
		return codeRoleTypeMap;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
